branches:
  - name: master
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "Code Quality Checks"
          - "Unit Tests"
          - "Build APK"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      restrictions: null

  - name: development
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "Code Quality Checks"
          - "Unit Tests"
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      restrictions: null
