name: Android CI/CD

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  test:
    name: City Input Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run City Input Tests
        run: ./gradlew :features:city-input:test --stacktrace

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: features/city-input/build/reports/tests/
          retention-days: 7

  build:
    name: Build APK
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set Weather API Key
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: |
          echo "WEATHER_API_KEY=\"$WEATHER_API_KEY\"" >> ./local.properties

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            app/build/outputs/apk/debug/
            app/build/reports/
            features/*/build/reports/
          retention-days: 7
